service: whosout
frameworkVersion: ">=1.60.5"

plugins:
    - serverless-pseudo-parameters

custom:
    stage: ${opt:stage}
    region: ${opt:region}

provider:
  name: aws
  runtime: python3.7
  stackTags:
    stage: ${opt:stage}
    owner: mike-p
    service: whosout
    feature: slack-command
    tenant: peak
  versionFunctions: false
  environment:
    region: ${opt:region}
    stage: ${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:lambda:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':function:whosout-'
            - ${opt:stage}
            - '-slackSlashCommand*'
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      # Resource: {Ref: Secrets}
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:secretsmanager:'
            - Ref: 'AWS::Region'
            - ':'
            - Ref: 'AWS::AccountId'
            - ':secret:whosout-slackcommand-secrets-*'

layers:
  Pandas:
    path: layers/pandas
    name: ${self:service}-Py-Pandas    # optional, Deployed Lambda layer name
    description: Pandas python module  # optional, Description to publish to AWS
    compatibleRuntimes:
      - python3.7
    licenseInfo: GPL-3.0-or-later
  Moment:
    path: layers/moment
    name: ${self:service}-Py-Moment    # optional, Deployed Lambda layer name
    description: Moment python module  # optional, Description to publish to AWS
    compatibleRuntimes:
      - python3.7
    licenseInfo: GPL-3.0-or-later

package:
  individually: true

functions:
  slackSlashCommand:
    handler: slackSlashCommand.lambda_handler

  slackSlashCommandReturn:
    handler: slackSlashCommandReturn.lambda_handler
    layers:
      - {Ref: PandasLambdaLayer}
      - {Ref: MomentLambdaLayer}
      - "arn:aws:lambda:#{AWS::Region}:113088814899:layer:Klayers-python37-numpy:10"
      - "arn:aws:lambda:#{AWS::Region}:113088814899:layer:Klayers-python37-requests:15"
    ### HTTP endpoints (not rest) not available with serverless yet :(
    ### Use CloudFormation instead
    # events:
    #     - http:
    #         path: /whosout
    #         method: post
    #         cors: true

resources:
  Description: Resources for Whos Out BambooHR slack command
  Resources:
    ### HTTP endpoints (not rest) not available with serverless yet :(
    ### Use CloudFormation instead
    Endpoint:
        Type: AWS::ApiGatewayV2::Api
        Properties:
            Name:
                Fn::Join:
                    - ""
                    - - "whosout-slack-endpoint-"
                      - ${opt:stage}
            Description: API Endpoint for the WhosOut BambooHR slack command
            CorsConfiguration:
                AllowMethods: 
                    - POST
            ProtocolType: HTTP
            Tags:
                stage: ${opt:stage}
                owner: mike-p
                service: whosout
                feature: slack-command
                tenant: peak
    EndpointStage:
        Type: AWS::ApiGatewayV2::Stage
        Properties:
            StageName: ${opt:stage}
            ApiId: !Ref Endpoint
            AutoDeploy: true
            Tags:
                stage: ${opt:stage}
                owner: mike-p
                service: whosout
                feature: slack-command
                tenant: peak
    EndpointRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties: 
            ApiId: !Ref Endpoint
            RouteKey: "$default"
            # RouteKey:
            #     Fn::Join:
            #         - "/"
            #         - - "POST"
            #           - ${opt:stage}
            Target:
                Fn::Join:
                    - "/"
                    - - "integrations"
                      - !Ref EndpointIntegration
    EndpointIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties: 
            ApiId: !Ref Endpoint
            Description: API Endpoint Integration for the WhosOut BambooHR slack command
            IntegrationType: AWS_PROXY
            IntegrationMethod: POST
            # NOTE: The Integration URI would change if the service or handler name changes
            IntegrationUri: !Join 
                - ''
                - - 'arn:aws:apigateway:'
                  - !Ref 'AWS::Region'
                  - ':lambda:path/2015-03-31/functions/arn:aws:lambda:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':function:whosout'
                  - '-'
                  - ${opt:stage}
                  - '-slackSlashCommand/invocations'
            PayloadFormatVersion: "1.0"
    ExecuteLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !Join 
          - ''
          - - 'arn:aws:lambda:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':function:whosout-'
            - ${opt:stage}
            - '-slackSlashCommand'
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: !Join 
          - ''
          - - 'arn:aws:execute-api:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':'
            - !Ref Endpoint
            - '/*/*/whosout-'
            - ${opt:stage}
            - '-slackSlashCommand'
    # Secrets:
    #     Type: 'AWS::SecretsManager::Secret'
    #     DeletionPolicy: Retain
    #     Properties:
    #       Name:
    #         Fn::Join:
    #             - ""
    #             - - "whosout-slackcommand-secrets-"
    #               - ${opt:stage}
    #       Description: Store the secret values used for the Whos Out BambooHR slack command
    #       SecretString: '{"TokenName":"Default"}'
    #       Tags:
    #           - Key: stage
    #             Value: ${opt:stage}
    #           - Key: owner
    #             Value: mike-p
    #           - Key: service
    #             Value: whosout
    #           - Key: feature
    #             Value: slack-command
    #           - Key: tenant
    #             Value: peak
